sqlite, cgosqlite: fix TestTrace on macOS
	--- FAIL: TestTrace (0.00s)
	    sqlite_test.go:522: trace: improbable duration: -513288h42m26.15796988s
	    sqlite_test.go:523: trace: improbable duration: -513288h42m26.15796988s
	    sqlite_test.go:558: trace: improbable duration: 0s

Two problems:

1. It turns out CLOCK_MONOTONIC is 6 on macOS. Oops.
   My comment claims it was defined as 1 in the POSIX spec,
   but now I can't find it. So I can only say it's 1 on linux.

2. clock_gettime does not seem to have much resolution on
   macOS, so I see some zeros. Ignore them.