cgosqlite: use POSIX 2014 explicitly
Unless this is defined a strict compiler will error with an implicit
definition error at least, or at worst will not even find a definition
as one may optionally not be provided at all:

```
  ./cgosqlite.h: In function 'monotonic_clock_gettime':
  ./cgosqlite.h:52:9: error: implicit declaration of function 'clock_gettime' [-Wimplicit-function-declaration]
    52 |         clock_gettime(CLOCK_MONOTONIC, t);
        |         ^~~~~~~~~~~~~
```

This resolves an earlier TODO, where crawshaw had observed
CLOCK_MONOTONIC not being defined.

As a very minor change: use the system import syntax for system imports.